# Generated by Django 4.0.2 on 2022-02-12 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='classCurrentCapacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentclass',
            name='classMaxCapacity',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='className',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.IntegerField(primary_key=True, serialize=False)),
                ('studentFirstName', models.CharField(max_length=300)),
                ('studentLastName', models.CharField(max_length=300)),
                ('studentRegisterDate', models.DateTimeField(auto_now_add=True)),
                ('studentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.studentclass')),
            ],
        ),
    ]
