# Generated by Django 4.0.1 on 2022-02-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_studentclass_classcurrentcapacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='className',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='createdDate',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='updateDate',
        ),
        migrations.AddField(
            model_name='studentclass',
            name='name',
            field=models.CharField(default='Empty Name', max_length=50),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
