# Generated by Django 4.0.1 on 2022-02-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_remove_studentclass_classname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentClass',
            new_name='ClassInfo',
        ),
    ]
