# Generated by Django 4.0.1 on 2022-02-02 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration_apps', '0002_alter_studentclass_max_capicity_studentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
