# Generated by Django 4.0.1 on 2022-02-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_apps', '0003_studentinfo_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name_plural': 'students'},
        ),
    ]
